[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"gdown==4.6.3",
	"nibabel==5.0.0",
	"tensorflowjs==4.2.0",
]

[project.optional-dependencies]
dev = [
	"mypy==1.0.0",
	"ruff==0.0.248",
]
