[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"gdown==4.6.4",
	"nibabel==5.0.1",
	"tensorflowjs==4.2.0",
]

[project.optional-dependencies]
dev = [
	"mypy==1.1.1",
	"ruff==0.0.254",
]
