[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"gdown==4.7.1",
	"nibabel==5.1.0",
	"tensorflowjs==4.10.0",
]

[project.optional-dependencies]
dev = [
	"black==22.12.0",
	"djlint==1.32.1",
	"mypy==1.5.1",
	"ruff==0.0.285",
	"ssort==0.11.6",
]
