[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"gdown==4.7.1",
	"nibabel==5.1.0",
	"tensorflowjs==4.11.0",
]

[project.optional-dependencies]
dev = [
	"black==23.9.1",
	"djlint==1.34.0",
	"mypy==1.5.1",
	"ruff==0.0.291",
	"ssort==0.11.6",
]
