[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"gdown==4.7.1",
	"nibabel==5.0.1",
	"tensorflowjs==4.3.0",
]

[project.optional-dependencies]
dev = [
	"mypy==1.2.0",
	"ruff==0.0.261",
]
